version: "3.8"
services:
  ngrinder-controller:
    container_name: ngrinder-controller-arm

    build:
      context: ./ngrinder-controller
      dockerfile: Dockerfile
    restart: always

    ports:
      - "8080:8080"     # nGrinder UI 포트
      - "12000-12100:12000-12100"  # nGrinder Agents 포트(에이전트 개수만큼 12000+@)
      - "16001:16001"   # nGrinder Controller 포트
    networks:
      - ngrinder

#    volumes:
#      - ./ngrinder-controller:/home/  # 컨테이너의 /home/과 호스트의 해당 디렉토리를 연결

  ngrinder-agent:
    container_name: ngrinder-agent-arm
    depends_on:
      - ngrinder-controller
    build:
      context: ./ngrinder-agent
      dockerfile: Dockerfile
    restart: always
#    volumes:
#      - ./ngrinder-agent:/home/  # 컨테이너의 /home/과 호스트의 해당 디렉토리를 연결

    networks:
      - ngrinder

networks:
  ngrinder:
    driver: bridge