version: "3.8"
services:
  ngrinder:
    container_name: arm_ngrinder

    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8080:8080"
      - "12000-12100:12000-12100"
      - "16001:16001"
